name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p proxy-pattern/usr/bin
        cp build/proxy_main proxy-pattern/usr/bin/
        mkdir -p proxy-pattern/DEBIAN
        cat > proxy-pattern/DEBIAN/control <<EOP
        Package: proxy-pattern
        Version: 1.0
        Architecture: amd64
        Maintainer: YAroslav10Ti
        Description: Proxy Pattern Implementation
        EOP
        dpkg-deb --build proxy-pattern
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: proxy-pattern
        path: proxy-pattern.deb
