name: Build and Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p proxy-pattern/usr/bin
        cp build/proxy_main proxy-pattern/usr/bin/
        mkdir -p proxy-pattern/DEBIAN
        echo "Package: proxy-pattern" > proxy-pattern/DEBIAN/control
        echo "Version: 1.0" >> proxy-pattern/DEBIAN/control
        echo "Architecture: amd64" >> proxy-pattern/DEBIAN/control
        echo "Maintainer: YAroslav10Ti" >> proxy-pattern/DEBIAN/control
        echo "Description: Proxy Pattern Implementation" >> proxy-pattern/DEBIAN/control
        dpkg-deb --build proxy-pattern
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: proxy-pattern
        path: proxy-pattern.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: proxy-pattern.deb
