name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полная история коммитов
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        
    - name: Clean and Build
      run: |
        rm -rf build
        mkdir -p build
        cd build
        cmake ..
        make
        
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
