---
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgtest-dev \
            tree

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Verify paths
        run: |
          echo "Working dir: $(pwd)"
          ls -l build/proxy_main
          mkdir -vp test_dir && rm -rf test_dir
      - name: Create DEB package
        run: |
          # Создаем структуру пакета
          mkdir -vp package/usr/bin package/DEBIAN
          
          # Устанавливаем бинарник
          install -v -m 0755 build/proxy_main package/usr/bin/
          
          # Создаем control файл
          cat <<EOL | tee package/DEBIAN/control
Package: proxy-pattern
Version: 1.0
Architecture: amd64
Maintainer: YAroslav10Ti
Description: Proxy Pattern Implementation
EOL

          # Проверяем структуру
          echo "=== Final package structure ==="
          tree -a package/
          
          # Собираем пакет
          dpkg-deb --root-owner-group --build package proxy-pattern.deb
          
          # Проверяем результат
          dpkg -I proxy-pattern.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy-pkg
          path: |
            proxy-pattern.deb
            build/proxy_main
