name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure || echo "Tests failed"

    - name: Create DEB package
    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin package/DEBIAN
        install -D build/proxy_main package/usr/bin/
        cat > package/DEBIAN/control <<EOL
Package: proxy-pattern
Version: 1.0
Architecture: amd64
Maintainer: YAroslav10Ti
Description: Proxy Pattern Implementation
EOL
        dpkg-deb --build package proxy-pattern.deb
        ls -lh *.deb
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxy-pattern
        path: |
          package.deb
          build/proxy_main

    - name: Create Release
      if: github.ref == 'refs/heads/main' && success()
      uses: softprops/action-gh-release@v2
      with:
        files: package.deb
        body: |
          Автоматическая сборка:
          - Версия: 1.0
          - Дата: $(date -u +'%Y-%m-%d')
          - Хеш коммита: ${{ github.sha }}

    - name: Create Release
      if: github.ref == 'refs/heads/main' && success()
      uses: softprops/action-gh-release@v2
      with:
        files: package.deb
        body: |
          Автоматическая сборка:
          - Версия: 1.0
          - Дата: $(date -u +'%Y-%m-%d')
          - Хеш коммита: ${{ github.sha }}
