---
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Create DEB package
        run: |
          mkdir -p package/usr/bin package/DEBIAN
          install -m 0755 -D build/proxy_main package/usr/bin/
          cat <<EOL > package/DEBIAN/control
Package: proxy-pattern
Version: 1.0
Architecture: amd64
Maintainer: YAroslav10Ti
Description: Proxy Pattern Implementation
EOL
          dpkg-deb --root-owner-group --build package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy-pattern
          path: |
            package.deb
            build/proxy_main
