---
name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgtest-dev \
            tree

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Create DEB package
        run: |
          set -e
          echo "=== Creating package structure ==="
          mkdir -p package/usr/bin package/DEBIAN
          
          echo "=== Verifying binary ==="
          if [ ! -f build/proxy_main ]; then
            echo "##[error]Binary file not found in build/"
            ls -l build/
            exit 1
          fi
          
          echo "=== Installing binary ==="
          install -m 0755 build/proxy_main package/usr/bin/
          
          echo "=== Creating control file ==="
          cat <<'EOL' > package/DEBIAN/control
Package: proxy-pattern
Version: 1.0
Architecture: amd64
Maintainer: YAroslav10Ti
Description: Proxy Pattern Implementation
EOL
          
          echo "=== Building package ==="
          dpkg-deb --root-owner-group --build package
          
          echo "=== Verifying package ==="
          dpkg -I package.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: package.deb
